services:
  app:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
        GAP_VERSION: ${GAP_VERSION}
    environment:
      WORKDIR:
      USER:
      USER_ID:
    ports:
      - "8888:8888"
    image: ${IMAGE_NAME}:${GAP_VERSION}
    container_name: gap-app
    volumes:
      - ./start.sh:/opt/start.sh
      - ./workspace:${WORKDIR}
    working_dir: ${WORKDIR}
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root 
