version: '3'
services:
  gap:
    build:
      context: .
      args:
        GAP_VERSION:
    container_name: "gap-slim"
    image: ${IMAGE}
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--no-browser"]