services:
  app:
    image: ghcr.io/psistwu/gap-docker:${GAP_VERSION}
    environment:
      WORKDIR:
      JUPYTER_TOKEN:
    ports:
      - "8888:8888"
    container_name: gap-docker
    volumes:
      - ./workspace:${WORKDIR}
    working_dir: ${WORKDIR}
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root
