version: '3'
services:
  workspace:
    build:
      context: .
      args:
        GAP_VERSION:
        CXSC_VERSION:
        FPLLL_VERSION:
        SINGULAR_VERSION:
        SINGULAR_PATCH:
        _4TI2_VERSION:
        PARI_VERSION:
    image: ${IMAGE}
    network_mode: host
    ports:
      - "8888:8888"
